# Generated by Django 4.2.6 on 2023-10-31 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("educationapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="place",
            new_name="actor",
        ),
    ]
